### PR TITLE
Enable menu shadows for non-KDE desktops

### PR DESCRIPTION
**Pull request by CDrummond**
Noticed that popup menus, etc, did not have shadows. This seems to fix the issue for me.

### CODE REVIEW

**Comment by MartinBriza** [comment]
Not sure if looking into the environment is a good idea when Qt does the detection somewhere internally. I'll have to look where and how is this done so we can utilize that instead eventually. In case it's a private API, this will have to suffice.

**Comment by CDrummond** [comment]
OK. I guess just remove the setTranslucentBackground function - as it should not be needed. I left it in there so that KDE desktops would not be affected by this. But with it left as before, then there are no menu shadows in gnome shell.

**Comment by DoctorJellyface** [comment]
Not true, GTK+ 3 apps draw their own but all others get a 1px shadow around them.

**Comment by CDrummond** [comment]
Which version of gnome? Under Ubuntu 16.10, for me without this patch popup menus (e.g. context menus) do not have shadow - they do have a 1 pix dark border, but no shadow.

**Comment by MartinBriza** [comment]
Here in Fedora on 3.22 there are no shadows either.

2017-02-13 15:00 GMT+01:00 CraigD <notifications@github.com>:

**Comment by CDrummond** [comment]
Looking at Qt's source code - it too uses XDG_CURRENT_DESKTOP to determine the desktop environment.

**Comment by MartinBriza** [comment]
Ok, I don't see harm in this.

**Comment by MartinBriza** [comment]
That's what I wanted to do

**Comment by DoctorJellyface** [comment]
If it doesn’t place any shadows the menu windows must have a wrong/different class.

**Comment by MartinBriza** [comment]
I see a very slight shadow in menus with gnome 3.22.2

**Comment by DoctorJellyface** [comment]
They should look better in 3.24, my patch fixing them got merged.

**Comment by DoctorJellyface** [comment]
But now I’m thinking about it it’s probably better to make them manually, like GTK+ 3 does, because the Mutter shadows are really just a cheap copy, it wasn’t possible to recreate a solid 1px border.

**Comment by MartinBriza** [comment]
Can you please illustrate what exactly do you mean? There is a shadow in
menus now and I don't see a difference from what GTK applications have.

2017-02-27 11:51 GMT+01:00 Juraj Fiala <notifications@github.com>:

**Comment by DoctorJellyface** [comment]
Sure.

gtk-qt-shadows

**Pull request merged**
