### PR TITLE
Use xprop to set _GTK_THEME_VARIANT="dark" for dark variant. 

### PR DESCRIPTION
**Pull request by CDrummond**
Causes dark titlebars under GNOME shell.

Not 100% sure about this, as it uses an external app - but at least it has no X11 dep?

### CODE REVIEW

**Comment by MartinBriza** [comment]
Not sure about this either, especially considering this is a matter of the window manager. There is QGnomePlatform that works the other way around - if the environment around is dark, we'll be dark too.

What do you think? I'd love some feedback from people who are not using GNOME but are using Adwaita.

**Comment by CDrummond** [comment]
Well - with this fix  it can be on a per-app basis. For instance, I have Digikam5 setup to use Adwaita-Dark, but I use Adwaita elsewhere. With this Digikam5 gets the dark titlebar, but Gedit still gets the light one - i.e. this works the same as per Gtk apps.

**Comment by MartinBriza** [comment]
Ah, yes, that's what i thought in the morning when i read the PR first but
then forgot about it :) Ok, I think we can add this in some controlled
fashion. I'll see if there is a cleaner way of doing it than creating
another process.

2017-02-13 14:48 GMT+01:00 CraigD <notifications@github.com>:

**Comment by DoctorJellyface** [comment]
@CDrummond curious, how do you use it on a per app basis? Do you use this patch?

**Comment by MartinBriza** [comment]
You can have a custom .desktop file for it, with "-style adwaita-dark" in
the arguments.

2017-02-13 14:52 GMT+01:00 Juraj Fiala <notifications@github.com>:

**Comment by CDrummond** [comment]
Digikam5 has a option to configure the widget style, For general Qt apps you can just pass "-style adwaita-dark" when running (or edit the .desktop file)

I agree the process calling is not nice - but its an X property, and I didn't want to add explicit links to X.

**Comment by DoctorJellyface** [comment]
@MartinBriza @CDrummond does that make the titlebar dark however?

**Comment by MartinBriza** [comment]
It does not but with this patch it would.

2017-02-13 14:54 GMT+01:00 Juraj Fiala <notifications@github.com>:

**Comment by CDrummond** [comment]
Please close this pull request. I've started on a new one where I dynamically load X11 (if platform is 'xcb') and use the X function calls to set the property. This means no QProcess required, and no need for adwaita to explicitly link to X11.

**Pull request closed without merging**
